/// Flutter icons OverAllAppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OverAllAppIcons
///      fonts:
///       - asset: fonts/OverAllAppIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons();

  static const String _kFontFam = 'OverAllAppIcons';

  static const IconData footerPracticeIcon =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData footerTestIcon =
      IconData(0xe801, fontFamily: _kFontFam);
  static const IconData linkClickIcon = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData backArrow = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ugcNetIcon = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData profileIcon = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData referAFriendIcon =
      IconData(0xe806, fontFamily: _kFontFam);
  static const IconData settingIcon = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData aboutIcon = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData starIcon = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData helpIcon = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData logoutIcon = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData myProfileIcon = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData mySubscriptionIcon =
      IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData attemptedTestIcon =
      IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData ntaTestPaperIcon =
      IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData incompleteTestIcon =
      IconData(0xe810, fontFamily: _kFontFam);
  static const IconData customTestIcon =
      IconData(0xe811, fontFamily: _kFontFam);
  static const IconData readyTestIcon = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData testStatusIcon =
      IconData(0xe813, fontFamily: _kFontFam);
  static const IconData practiceProgressIcon =
      IconData(0xe814, fontFamily: _kFontFam);
  static const IconData filterIcon = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData arrow = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData selectOptionIcon =
      IconData(0xe817, fontFamily: _kFontFam);
  static const IconData optionSelectedIcon =
      IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData footerHomeIcon =
      IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData footerMoreIcon =
      IconData(0xe820, fontFamily: _kFontFam);
  static const IconData scoreIcon = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData questionBreakdownIcon =
      IconData(0xe823, fontFamily: _kFontFam);
  static const IconData alertErrorIcon =
      IconData(0xe824, fontFamily: _kFontFam);
  static const IconData ntaTestPaperArrow =
      IconData(0xe825, fontFamily: _kFontFam);
  static const IconData changeCourseIcon =
      IconData(0xe826, fontFamily: _kFontFam);
  static const IconData averageResultIcon =
      IconData(0xe827, fontFamily: _kFontFam);
  static const IconData loading = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData jumpIcon = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData progressIcon = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData accuracyIcon = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData chapterBreakdownIcon =
      IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData noTestGivenIcon =
      IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData noQuestionAnsweredIcon =
      IconData(0xe818, fontFamily: _kFontFam);
}
